name: Flutter Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter - version: '3.0.0' # 根据实际需要设置Flutter版本
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter project
        run: flutter build macos # 这里可以根据需要改为其他构建目标，如flutter build ios、flutter build web等
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_FOR_FLUTTER }}
        with:
          tag_name: v1.0.0
          # 使用从Git标签获取并设置的变量作为release_name的值
          release_name: Release v1.0.0
          draft: false
          prerelease: false
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Flutter-app
          path: build/macos
          upload-to-release: ${{ steps.create_release.outputs.id }}
