name: Flutter Build
on:
  push:
    tags:
      - 'v*.*.*' # 仅在推送以 v 开头的语义化版本标签时触发该工作流程，确保是正式的版本发布操作
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter - version: '3.0.0' # 根据实际需要设置Flutter版本
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter project
        run: flutter build macos # 这里可以根据需要改为其他构建目标，如flutter build ios、flutter build web等
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_FOR_FLUTTER }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload MacOS Application to Release
        uses: actions/upload-artifact@v3
        with:
          name: Flutter-MacOS-App
          path: build/macos/Build/Products/Release
          upload-to-release: ${{ steps.create_release.outputs.id }}
